config_version = 2

[audio]
enable_overdrive = true
enable_sounds = true

[backdrop]
blur_intensity = 0.13999999687075615
enabled = true
tint_intensity = 0.53999998793005943

[bar]
order = [ "main", "leftbar" ]

    [bar.leftbar]
    auto_hide = true
    background_opacity = 0.25999999418854713
    capsule = true
    center = []
    contact_shadow = true
    enabled = true
    end = [ "active_window", "custom_button_2", "custom_button_3", "custom_button_4" ]
    layer = "overlay"
    margin_ends = 300
    padding = 30
    position = "left"
    reserve_space = false
    start = [ "clipboard", "screenshot", "tray" ]

    [bar.main]
    end = [ "cat", "media", "weather", "tray", "volume", "group:g1" ]
    smart_auto_hide = true
    start = [ "launcher", "workspaces", "group:g2" ]

        [[bar.main.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "network", "clipboard", "bluetooth", "battery", "notifications" ]
        opacity = 1.0
        padding = 6.0

        [[bar.main.capsule_group]]
        border = ""
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "wallhaven", "wallpaper" ]
        opacity = 0.69999998807907104
        padding = 6.0

[brightness]
sync_all_monitors = true

[calendar]
enabled = true

    [calendar.account.home_nextcloud]
    name = "Victor"
    type = "google"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "clipboard"

[[control_center.shortcuts]]
type = "keyboard_layout"

[[control_center.shortcuts]]
type = "audio"

[[control_center.shortcuts]]
type = "mic_mute"

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000006"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = false

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 16.0
    box_width = 2118.5595703125
    cx = 1031.905517578125
    cy = 1075.927978515625
    output = "HDMI-A-1"
    rotation = -3.1397311687469482
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background_opacity = 0.0
        bands = 116
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 84.3984375
    box_width = 275.2734375
    cx = 151.77734375
    cy = 75.61328125
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background_color = "surface"
        background_opacity = 0.5
        background_padding = 0
        background_radius = 0
        center_text = true
        clock_style = "digital"
        color = "primary"
        format = "{:%H:%M}"
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 171.9375
    box_width = 61.05859375
    cx = 258.166015625
    cy = 204.0234375
    output = "HDMI-A-1"
    rotation = -0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background_opacity = 0.5
        background_padding = 0
        background_radius = 0
        center_text = true
        clock_style = "digital"
        format = "{:%d%n%m%n %y }"

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 172.26171875
    box_width = 213.34375
    cx = 121.2890625
    cy = 203.248046875
    output = "HDMI-A-1"
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background_opacity = 0.5
        background_padding = 4
        background_radius = 0
        color = "on_surface"
        forecast_days = 3
        show_forecast = true

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 280.234375
    output = "HDMI-A-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        background = false
        bar_width = 0.69999999999999996
        bloom_intensity = 0.95000000000000007
        inner_diameter = 0.75
        ring_opacity = 0.60000000000000009
        sensitivity = 1.1000000000000001
        visualization_mode = "bars_rings"

[dock]
active_monitor_only = true
auto_hide = false
launcher_position = "start"
reserve_space = false
show_dots = true
smart_auto_hide = true

[hot_corners]
enabled = true

    [hot_corners.bottom_left]
    action = "launcher"

    [hot_corners.top_left]
    action = "window_switcher"

    [hot_corners.top_right]
    action = "control_center"

[idle]
behavior_order = [ "lock", "screen-off" ]

    [idle.behavior.lock]
    action = "lock"
    command = "noctalia:screen-lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    command = "noctalia:dpms-off"
    enabled = true
    resume_command = "noctalia:dpms-on"
    timeout = 1000.0

[location]
address = "Montreal"

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 176.0
    box_width = 192.0
    cx = 960.0
    cy = 108.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_color = "on_surface"
        background_opacity = 0.0
        center_text = false
        clock_style = "analog"
        color = "on_surface"
        forecast_days = 3
        shadow = false
        show_forecast = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 144.0
    box_width = 544.0
    cx = 128.0
    cy = 1008.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background_opacity = 0.0
        clock_style = "digital"
        format = "{:%-I:%M %p}"
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 222.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background_opacity = 0.0
        shadow = false
        show_forecast = false
        stat = "net_rx"
        stat2 = ""

[nightlight]
enabled = true

[notification]
layer = "overlay"

[plugin_settings."noctalia/wallhaven"]
api_key = "X3sguUcft78OWq8tJq1wdUlyeQxWz1pL"
download_dir = "~/Pictures/wallpapers"

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/wallhaven" ]

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
app_icon_color = "secondary"
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = false

    [shell.greeter_sync]
    auto_sync = false

    [shell.launcher]
    app_grid = true

    [shell.panel]
    launcher_app_grid = true
    launcher_placement = "attached"
    launcher_position = "auto"
    launcher_session_search = true
    polkit_placement = "attached"
    session_placement = "floating"

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "ghostty", "niri" ]
    community_ids = [ "obsidian", "vscode" ]

[wallpaper]
directory = "/home/avanonyme/Pictures/Wallpapers"
transition_duration = 9600
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/avanonyme/Pictures/Wallpapers/958232.jpg"

    [wallpaper.last]
    path = "/home/avanonyme/Pictures/Wallpapers/958232.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/avanonyme/Pictures/Wallpapers/958232.jpg"

[weather]
unit = "metric"

[widget.cat]
audio_spectrum = true
scale = 1.5
tappy_mode = true
type = "noctalia/bongocat:cat"
use_mpris_filter = true

[widget.control-center]
glyph = "leaf-2"

[widget.custom_button_2]
glyph = "hexagon-number-1"
type = "custom_button"

[widget.custom_button_3]
glyph = "hexagon-number-2"
type = "custom_button"

[widget.custom_button_4]
glyph = "hexagon-number-3"
type = "custom_button"

[widget.launcher]
custom_image_colorize = true
glyph = "grid-dots"

[widget.media]
album_art_only = true
hide_when_no_media = true

[widget.taskbar]
group_by_workspace = true
only_active_workspace = true

[widget.wallhaven]
glyph = "photo-down"
type = "noctalia/wallhaven:wallhaven"

[widget.wallpaper]
capsule = true
glyph = "brand-google-photos"
interactive = false

[widget.workspaces]
display = "name"
hide_when_empty = true
labels_only_when_occupied = true