# This is a default home.nix generated by the follwing hone-manager command
# 
# home-manager init ./

{ config, lib, outputs, pkgs, ... }:

{
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = lib.mkDefault "avanonyme";
  home.homeDirectory = lib.mkDefault "/home/${config.home.username}";

  nixpkgs = {
  #outputs is not recognised
  # overlays = [
  #  outputs.overlays.additions
  #  ouputs.overlays.modifications
  #  outputs.overlays.stable-packages
  # ];
   config = {
    allowUnfree = true;
    allowUnfreePredicate = _: true;

   };
  };

  nix = {
   package = lib.mkDefault pkgs.nix;
   settings = {
    experimental-features = ["nix-command" "flakes"];
    warn-dirty = false;
   };
  };
  
  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "24.05"; # Please read the comment before changing.

  

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = with pkgs;[
   atlauncher #minecraft launcher
   bat #moder replacemement for cat
   btop #resources monitoring
   bitwarden-desktop
   celluloid #media player
   dunst #notif daemon
   feh #image viewer
   flameshot #screenshot
   gh #github in the terminal
   gimp #image editing
   git
   lutris #open gaming
   nomacs #image editing
   neovim
   neofetch #sys info
   mako #notif daemon for wayland
   protonup #proton/wine management
   obsidian
   transmission_4-qt #torrent client
   qemu #virtualization
   slurp #wayland screenshot area selection
   synergy #same keyboard for local network
   tldr
   unzip
   tree #directory visualisation
   vlc #media player
   wl-clipboard #wayland clipboard management
  ];

  # Home Manager is pretty good at managing dotfiles. The primary way to manage
  # plain files is through 'home.file'.
  home.file = {
    # # Building this configuration will create a copy of 'dotfiles/screenrc' in
    # # the Nix store. Activating the configuration will then make '~/.screenrc' a
    # # symlink to the Nix store copy.
    # ".screenrc".source = dotfiles/screenrc;

    # # You can also set the file content immediately.
    # ".gradle/gradle.properties".text = ''
    #   org.gradle.console=verbose
    #   org.gradle.daemon.idletimeout=3600000
    # '';
  };

  # Home Manager can also manage your environment variables through
  # 'home.sessionVariables'. If you don't want to manage your shell through Home
  # Manager then you have to manually source 'hm-session-vars.sh' located at
  # either
  #
  #  ~/.nix-profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  /etc/profiles/per-user/m3tam3re/etc/profile.d/hm-session-vars.sh
  #
  home.sessionVariables = {
    # EDITOR = "emacs";
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

    home.sessionVariables = {
    STEAM_EXTRA_COMPAT_TOOLS_PATHS =
      "\\\${HOME}/.steam/root/compatibilitytools.d";
  };

  programs.git ={
   enable = true;
   userName = "avanonyme";
   userEmail = "avanix26@protonmail.com";
   extraConfig = {
    init.defaultBranch = "main";
    safe.directory = "/home/avanonyme/.dotfiles";
   };
  };

  # services.transmission = { 
#    enable = true; #Enable transmission daemon
#    openRPCPort = true; #Open firewall for RPC
#    settings = { #Override default settings
#      rpc-bind-address = "0.0.0.0"; #Bind to own IP
#      rpc-whitelist = "127.0.0.1,10.0.0.1"; #Whitelist your remote machine (10.0.0.1 in this example)
#    };
#  };

}
